"use client";
import { motion } from "framer-motion";
import { BookOpen, Check, ChevronDown, Lightbulb, MessageCircleMore, Sparkles, WandSparkles } from "lucide-react";
import type { Feedback, Improvement } from "@/types/feedback";

function ArrowRow({item}:{item:{original:string;correction?:string;suggestion?:string;explanation:string}}){const change=item.correction||item.suggestion||"";return <div className="border-b border-[var(--line)] py-5 last:border-0"><div className="grid gap-2 sm:grid-cols-[1fr_24px_1fr]"><span className="font-medium text-[var(--red)] line-through decoration-red-300">{item.original}</span><span className="hidden text-center text-[var(--muted)] sm:block">↓</span><span className="font-semibold text-[var(--green)]">{change}</span></div><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.explanation}</p></div>}
function ImprovementCard({item,kind}:{item:Improvement;kind:"vocabulary"|"expression"}){return <article className="rounded-2xl border border-[var(--line)] bg-white/55 p-5 dark:bg-slate-900/30"><div className="flex items-start gap-3"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${kind==="expression"?"bg-blue-50 text-[var(--blue)] dark:bg-blue-950":"bg-amber-50 text-[var(--yellow)] dark:bg-amber-950"}`}>{kind==="expression"?<MessageCircleMore size={18}/>:<BookOpen size={18}/>}</div><div><p className="text-sm text-[var(--muted)]">Instead of <span className="font-medium text-[var(--ink)]">“{item.original}”</span></p><p className="mt-1 font-bold text-[var(--green)]">“{item.suggestion}”</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.explanation}</p></div></div></article>}
const scoreLabels={grammar:"Grammar",vocabulary:"Vocabulary",fluency:"Fluency",naturalness:"Naturalness",confidence:"Confidence"} as const;
export function FeedbackDashboard({feedback,onNewRecording}:{feedback:Feedback;onNewRecording:()=>void}){return <section id="feedback" className="bg-white/45 px-5 py-16 dark:bg-slate-950/20 sm:px-8 lg:px-12"><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="mx-auto max-w-6xl"><div className="mb-9 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-semibold text-[var(--green)]">Your feedback</p><h2 className="text-3xl font-bold tracking-[-.055em] sm:text-4xl">A clearer way to say it.</h2><p className="mt-2 text-[var(--muted)]">Small adjustments make a meaningful difference.</p></div><button onClick={onNewRecording} className="rounded-xl border border-[var(--line)] bg-white px-4 py-2.5 text-sm font-bold transition hover:border-[var(--green)] dark:bg-slate-900">Practice again</button></div>
<div className="grid gap-5 lg:grid-cols-3"><article className="glass rounded-3xl p-6 lg:col-span-2"><h3 className="font-bold">Original transcript</h3><p className="mt-4 rounded-2xl bg-slate-100/80 p-5 leading-8 text-[var(--muted)] dark:bg-slate-800">{feedback.transcript}</p><div className="mt-6 flex items-center gap-2"><WandSparkles size={18} className="text-[var(--green)]"/><h3 className="font-bold">Corrected version</h3></div><p className="mt-3 rounded-2xl bg-[var(--mint)] p-5 text-lg font-medium leading-8">{feedback.correctedVersion}</p></article><article className="glass rounded-3xl p-6"><div className="flex items-center gap-2"><Sparkles size={18} className="text-[var(--blue)]"/><h3 className="font-bold">Your speaking scores</h3></div><div className="mt-5 grid grid-cols-2 gap-4">{(Object.keys(scoreLabels) as (keyof typeof scoreLabels)[]).map((key,i)=><motion.div initial={{opacity:0,scale:.85}} animate={{opacity:1,scale:1}} transition={{delay:i*.08}} key={key} className="text-center"><div className="score-ring mx-auto grid h-20 w-20 place-items-center rounded-full p-1.5" style={{"--score":feedback.scores[key],"--color":key==="grammar"?"#07895e":key==="vocabulary"?"#8b5cf6":key==="fluency"?"#247fe9":key==="naturalness"?"#d99a00":"#ec7180"} as React.CSSProperties}><div className="grid h-full w-full place-items-center rounded-full bg-white text-lg font-bold dark:bg-slate-900">{feedback.scores[key]}</div></div><p className="mt-2 text-xs font-semibold text-[var(--muted)]">{scoreLabels[key]}</p></motion.div>)}</div></article></div>
<div className="mt-5 grid gap-5 lg:grid-cols-2"><article className="glass rounded-3xl p-6"><h3 className="font-bold">Grammar corrections</h3><div className="mt-2">{feedback.grammarCorrections.length?feedback.grammarCorrections.map((item,i)=><ArrowRow item={item} key={i}/>):<p className="py-6 text-[var(--muted)]">No major grammar changes needed. Nicely done.</p>}</div></article><article className="glass rounded-3xl p-6"><h3 className="font-bold">Fluency suggestions</h3><ul className="mt-4 space-y-4">{feedback.fluencySuggestions.map((item,i)=><li key={i} className="flex gap-3 text-sm leading-6"><Check className="mt-1 shrink-0 text-[var(--green)]" size={17}/><span>{item}</span></li>)}</ul>{feedback.pronunciationNotes.length>0&&<div className="mt-6 border-t border-[var(--line)] pt-5"><h4 className="font-bold">Pronunciation notes</h4>{feedback.pronunciationNotes.map((note,i)=><p key={i} className="mt-2 text-sm text-[var(--muted)]">{note}</p>)}</div>}</article></div>
<div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="space-y-4">{feedback.vocabularyImprovements.map((item,i)=><ImprovementCard item={item} kind="vocabulary" key={i}/>)}</div><div className="space-y-4">{feedback.naturalExpressions.map((item,i)=><ImprovementCard item={item} kind="expression" key={i}/>)}</div></div>
<article className="mt-5 rounded-3xl bg-[var(--ink)] p-7 text-white"><Lightbulb className="text-[#75e8bd]"/><p className="mt-4 max-w-2xl text-xl font-semibold leading-8">{feedback.encouragement}</p><p className="mt-2 text-sm text-blue-100">Keep practicing — confident English is built one conversation at a time.</p></article></motion.div></section>}
