"use client";
import { AnimatePresence, motion } from "framer-motion";
import { AlertCircle, ArrowRight, Mic, RotateCcw, Square, UploadCloud } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { Feedback } from "@/types/feedback";

type State = "idle" | "recording" | "processing" | "error";
const bars = Array.from({length: 34});

export function RecordingStudio({ onFeedback }: { onFeedback: (feedback: Feedback) => void }) {
 const [state,setState]=useState<State>("idle"), [seconds,setSeconds]=useState(0), [error,setError]=useState(""); const rec=useRef<MediaRecorder|null>(null), chunks=useRef<Blob[]>([]), stream=useRef<MediaStream|null>(null);
 useEffect(()=>{ if(state!=="recording") return; const id=window.setInterval(()=>setSeconds(n=>n+1),1000); return ()=>clearInterval(id);},[state]);
 useEffect(()=>()=>stream.current?.getTracks().forEach(t=>t.stop()),[]);
 const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 async function start(){ setError(""); try { const media=await navigator.mediaDevices.getUserMedia({audio:true}); stream.current=media; const supported=["audio/webm;codecs=opus","audio/webm","audio/mp4"].find(t=>MediaRecorder.isTypeSupported(t)); const recorder=new MediaRecorder(media, supported?{mimeType:supported}:undefined); chunks.current=[]; recorder.ondataavailable=e=>{if(e.data.size) chunks.current.push(e.data)}; recorder.onstop=()=>upload(new Blob(chunks.current,{type:recorder.mimeType||"audio/webm"})); rec.current=recorder; setSeconds(0); recorder.start(250); setState("recording"); } catch { setState("error"); setError("Microphone access is needed to record. Check your browser settings and try again."); } }
 function stop(){ rec.current?.stop(); stream.current?.getTracks().forEach(t=>t.stop()); setState("processing"); }
 async function upload(blob:Blob){ try { const data=new FormData(); data.append("audio",new File([blob],`speaking-practice.${blob.type.includes("mp4")?"mp4":"webm"}`,{type:blob.type||"audio/webm"})); const res=await fetch("/api/analyze",{method:"POST",body:data}); const body=await res.json(); if(!res.ok) throw new Error(body.error||"Analysis failed."); onFeedback(body as Feedback); setState("idle"); } catch(e) { setState("error"); setError(e instanceof Error?e.message:"We couldn't analyze that recording."); } }
 return <section id="practice" className="px-5 pb-20 pt-10 sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="mb-2 text-sm font-semibold text-[var(--green)]">Speaking practice</p><h2 className="text-3xl font-bold tracking-[-.05em] sm:text-4xl">Say it out loud.</h2><p className="mt-2 text-[var(--muted)]">Take your time. A minute or two is a great start.</p></div>{state!=="recording"&&<span className="hidden text-sm text-[var(--muted)] sm:block">Private, focused practice</span>}</div>
 <div className="glass overflow-hidden rounded-[2rem] p-5 sm:p-8"><div className="grid items-center gap-8 lg:grid-cols-[1fr_1.1fr]"><div className="order-2 lg:order-1"><p className="max-w-md text-lg leading-8 text-[var(--muted)]">Speak about your day, introduce yourself, or answer an interview question. When you finish, your coach will turn your words into a clear next step.</p><div className="mt-7 flex flex-wrap gap-3"><span className="rounded-full bg-[var(--mint)] px-3 py-1.5 text-sm font-medium text-[var(--green)]">English only</span><span className="rounded-full bg-blue-50 px-3 py-1.5 text-sm font-medium text-[var(--blue)] dark:bg-blue-950">Up to 10 MB</span></div></div>
 <div className="relative mx-auto flex min-h-[300px] w-full max-w-md flex-col items-center justify-center rounded-[1.75rem] border border-white/70 bg-gradient-to-br from-white/75 to-emerald-50/50 p-6 text-center dark:from-slate-800 dark:to-emerald-950"><AnimatePresence mode="wait">{state==="processing"?<motion.div key="processing" initial={{opacity:0}} animate={{opacity:1}} className="space-y-5"><div className="mx-auto h-20 w-20 animate-spin rounded-full border-4 border-emerald-100 border-t-[var(--green)]"/><div><h3 className="text-xl font-bold">Listening closely…</h3><p className="mt-2 text-sm text-[var(--muted)]">Transcribing and preparing your feedback</p></div></motion.div>:<motion.div key="recorder" initial={{opacity:0}} animate={{opacity:1}} className="w-full"><div className="relative mx-auto grid h-32 w-32 place-items-center"><span className={`absolute inset-0 rounded-full ${state==="recording"?"animate-ping bg-emerald-200/55":"bg-emerald-100/80"}`}/><button onClick={state==="recording"?stop:start} className={`relative grid h-24 w-24 place-items-center rounded-full text-white shadow-xl transition hover:scale-105 ${state==="recording"?"bg-[var(--red)]":"bg-[var(--green)]"}`} aria-label={state==="recording"?"Stop recording":"Start recording"}>{state==="recording"?<Square size={25} fill="currentColor"/>:<Mic size={31}/>}</button></div><p className="mt-5 text-4xl font-bold tabular-nums tracking-[-.06em]">{time}</p><p className="mt-2 text-sm font-medium text-[var(--muted)]">{state==="recording"?"Recording — tap to stop":"Ready when you are"}</p><div className={`wave mt-7 flex h-10 items-center justify-center gap-1.5 ${state==="recording"?"text-[var(--green)]":"text-slate-300"}`}>{bars.map((_,i)=><span key={i} style={{height:`${10+(i*17)%30}px`,animationDelay:`${i*60}ms`}}/>)}</div></motion.div>}</AnimatePresence></div></div>
 {state==="error"&&<div className="mt-6 flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:bg-red-950/30 dark:text-red-200"><AlertCircle className="mt-0.5 shrink-0" size={18}/><div><p>{error}</p><button onClick={()=>setState("idle")} className="mt-2 inline-flex items-center gap-1 font-bold underline"><RotateCcw size={15}/>Try again</button></div></div>}</div></div></section>;
}
